import type {
  AnalyticsSnapshot,
  Call,
  CallTurn,
  CallbackTask,
  Customer,
  KnowledgeDocument,
  Organization,
  Program,
  QAReview,
  Queue,
  Ticket,
} from "@/lib/types";

export const demoOrganizations: Organization[] = [
  {
    id: "org-brightconnect",
    name: "BrightConnect BPO",
    slug: "brightconnect-bpo",
    default_languages: ["English", "Hindi"],
  },
];

export const demoPrograms: Program[] = [
  {
    id: "program-acme",
    organization_id: "org-brightconnect",
    name: "Acme Insurance",
    slug: "acme-insurance",
    description: "Claims, policy status, and callback-heavy insurance support workflow.",
    languages: ["English", "Hindi"],
    verification_policy: {
      required_for: ["case_status"],
      allowed_identifiers: ["customer_code", "last4_phone"],
    },
    handoff_policy: {
      live_on: ["human_request", "angry", "verification_failures", "vip", "low_confidence"],
      callback_on_unavailable: true,
      low_confidence_threshold: 0.7,
    },
    disclosure_template_en:
      "Hello, you are speaking with VoiceOps Control for Acme Insurance. This conversation may be recorded for quality and support. How can I help you today?",
    disclosure_template_hi:
      "Namaste, aap VoiceOps Control se baat kar rahe hain. Yeh call quality aur support ke liye record ho sakti hai. Main aaj aapki kaise madad kar sakta hoon?",
  },
  {
    id: "program-healthplus",
    organization_id: "org-brightconnect",
    name: "HealthPlus",
    slug: "healthplus",
    description: "Benefits and reimbursement support with stronger escalation rules.",
    languages: ["English", "Hindi"],
    verification_policy: {
      required_for: ["case_status"],
      allowed_identifiers: ["customer_code", "last4_phone"],
    },
    handoff_policy: {
      live_on: ["human_request", "angry", "verification_failures", "vip", "low_confidence"],
      callback_on_unavailable: true,
      low_confidence_threshold: 0.68,
    },
    disclosure_template_en:
      "Hello, you are speaking with VoiceOps Control for HealthPlus. This conversation may be recorded. What do you need help with today?",
    disclosure_template_hi:
      "Namaste, aap HealthPlus support line par hain. Yeh call record ho sakti hai. Aaj aapko kis madad ki zarurat hai?",
  },
  {
    id: "program-travelsafe",
    organization_id: "org-brightconnect",
    name: "TravelSafe",
    slug: "travelsafe",
    description: "Travel insurance claims, trip cancellations, and emergency assistance.",
    languages: ["English"],
    verification_policy: {
      required_for: ["case_status", "claim_lookup"],
      allowed_identifiers: ["customer_code", "last4_phone"],
    },
    handoff_policy: {
      live_on: ["human_request", "angry", "verification_failures"],
      callback_on_unavailable: true,
      low_confidence_threshold: 0.72,
    },
    disclosure_template_en:
      "Hello, you are connected to TravelSafe support powered by VoiceOps. This call may be recorded. How can we assist you today?",
    disclosure_template_hi:
      "Namaste, aap TravelSafe support se jude hain. Yeh call record ho sakti hai. Hum aapki kaise sahayata kar sakte hain?",
  },
];

export const demoQueues: Queue[] = [
  {
    id: "queue-acme",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    name: "Acme Bilingual Queue",
    supported_languages: ["English", "Hindi"],
    business_hours_start: "09:00",
    business_hours_end: "18:00",
    timezone: "Asia/Kolkata",
    live_handoff_enabled: true,
    callback_enabled: true,
  },
  {
    id: "queue-healthplus",
    organization_id: "org-brightconnect",
    client_program_id: "program-healthplus",
    name: "HealthPlus Claims Queue",
    supported_languages: ["English", "Hindi"],
    business_hours_start: "09:00",
    business_hours_end: "18:00",
    timezone: "Asia/Kolkata",
    live_handoff_enabled: true,
    callback_enabled: true,
  },
  {
    id: "queue-travelsafe",
    organization_id: "org-brightconnect",
    client_program_id: "program-travelsafe",
    name: "TravelSafe Support Queue",
    supported_languages: ["English"],
    business_hours_start: "08:00",
    business_hours_end: "20:00",
    timezone: "Asia/Kolkata",
    live_handoff_enabled: true,
    callback_enabled: true,
  },
];

export const demoCustomers: Customer[] = [
  {
    id: "customer-rohit",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    full_name: "Rohit Sharma",
    phone_number: "+919876543210",
    email: "rohit@example.com",
    customer_code: "CUS-1001",
    language_preference: "English",
    vip: false,
  },
  {
    id: "customer-suman",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    full_name: "Suman Verma",
    phone_number: "+919876543111",
    email: "suman@example.com",
    customer_code: "CUS-1002",
    language_preference: "Hindi",
    vip: false,
  },
  {
    id: "customer-neha",
    organization_id: "org-brightconnect",
    client_program_id: "program-healthplus",
    full_name: "Neha Joshi",
    phone_number: "+919123456789",
    email: "neha@example.com",
    customer_code: "CUS-2001",
    language_preference: "Hindi",
    vip: true,
  },
  {
    id: "customer-arjun",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    full_name: "Arjun Mehta",
    phone_number: "+919988776655",
    email: "arjun@example.com",
    customer_code: "CUS-1003",
    language_preference: "English",
    vip: false,
  },
  {
    id: "customer-vikram",
    organization_id: "org-brightconnect",
    client_program_id: "program-travelsafe",
    full_name: "Vikram Patel",
    phone_number: "+919090909090",
    email: "vikram@example.com",
    customer_code: "CUS-3001",
    language_preference: "English",
    vip: false,
  },
  {
    id: "customer-pooja",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    full_name: "Pooja Nair",
    phone_number: "+919998012345",
    email: "pooja@example.com",
    customer_code: "CUS-1004",
    language_preference: "Hindi",
    vip: false,
  },
];

export const demoCalls: Call[] = [
  {
    id: "call-001245",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    queue_id: "queue-acme",
    customer_id: "customer-rohit",
    customer_phone: "+91 98765 43210",
    status: "active",
    session_state: "answer_or_tool_action",
    disposition: "open",
    resolution_status: "in_progress",
    language: "English",
    sentiment: "neutral",
    intent: "case_status",
    confidence: 0.88,
    verification_state: "verified",
    failed_verification_attempts: 0,
    summary: "Claim CLM-9001 is under review after documents were received today.",
    escalation_reason: "",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: null,
    started_at: "2026-06-24T10:15:00.000Z",
    ended_at: null,
    display_call_id: "C-001245",
    customer_name: "Rohit Sharma",
    program_name: "Acme Insurance",
    duration_label: "03:24",
    display_status: "AI in Progress",
    agent_name: null,
    agent_initials: null,
  },
  {
    id: "call-001244",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    queue_id: "queue-acme",
    customer_id: "customer-suman",
    customer_phone: "+91 98765 43111",
    status: "active",
    session_state: "verification_if_needed",
    disposition: "open",
    resolution_status: "in_progress",
    language: "Hindi",
    sentiment: "neutral",
    intent: "case_status",
    confidence: 0.82,
    verification_state: "pending",
    failed_verification_attempts: 0,
    summary: "Customer requesting case status update, awaiting verification.",
    escalation_reason: "",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: null,
    started_at: "2026-06-24T10:17:00.000Z",
    ended_at: null,
    display_call_id: "C-001244",
    customer_name: "Suman Verma",
    program_name: "Acme Insurance",
    duration_label: "01:52",
    display_status: "Verifying",
    agent_name: null,
    agent_initials: null,
  },
  {
    id: "call-001243",
    organization_id: "org-brightconnect",
    client_program_id: "program-healthplus",
    queue_id: "queue-healthplus",
    customer_id: "customer-neha",
    customer_phone: "+91 91234 56789",
    status: "active",
    session_state: "live_handoff",
    disposition: "escalated",
    resolution_status: "handoff_in_progress",
    language: "Hindi",
    sentiment: "angry",
    intent: "human_transfer",
    confidence: 0.95,
    verification_state: "verified",
    failed_verification_attempts: 0,
    summary: "Customer policy claim is showing rejected. Wants reason and next steps.",
    escalation_reason: "Customer requested human",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: "live",
    started_at: "2026-06-24T10:12:00.000Z",
    ended_at: null,
    display_call_id: "C-001243",
    customer_name: "Neha Joshi",
    program_name: "HealthPlus",
    duration_label: "06:18",
    display_status: "Handoff Requested",
    agent_name: "Anita S.",
    agent_initials: "AS",
  },
  {
    id: "call-001242",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    queue_id: "queue-acme",
    customer_id: "customer-arjun",
    customer_phone: "+91 99887 76655",
    status: "active",
    session_state: "live_handoff",
    disposition: "escalated",
    resolution_status: "handoff_in_progress",
    language: "English",
    sentiment: "neutral",
    intent: "new_complaint",
    confidence: 0.79,
    verification_state: "verified",
    failed_verification_attempts: 0,
    summary: "Premium auto-debit failed, requesting manual correction.",
    escalation_reason: "Agent joined live",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: "live",
    started_at: "2026-06-24T10:10:00.000Z",
    ended_at: null,
    display_call_id: "C-001242",
    customer_name: "Arjun Mehta",
    program_name: "Acme Insurance",
    duration_label: "08:07",
    display_status: "Agent Joined",
    agent_name: "Rohit K.",
    agent_initials: "RK",
  },
  {
    id: "call-001241",
    organization_id: "org-brightconnect",
    client_program_id: "program-travelsafe",
    queue_id: "queue-travelsafe",
    customer_id: "customer-vikram",
    customer_phone: "+91 90909 90909",
    status: "active",
    session_state: "answer_or_tool_action",
    disposition: "open",
    resolution_status: "in_progress",
    language: "English",
    sentiment: "neutral",
    intent: "case_status",
    confidence: 0.91,
    verification_state: "verified",
    failed_verification_attempts: 0,
    summary: "Trip cancellation claim status lookup in progress.",
    escalation_reason: "",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: null,
    started_at: "2026-06-24T10:16:00.000Z",
    ended_at: null,
    display_call_id: "C-001241",
    customer_name: "Vikram Patel",
    program_name: "TravelSafe",
    duration_label: "02:41",
    display_status: "AI in Progress",
    agent_name: null,
    agent_initials: null,
  },
  {
    id: "call-001240",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    queue_id: "queue-acme",
    customer_id: "customer-pooja",
    customer_phone: "+91 99980 12345",
    status: "active",
    session_state: "live_handoff",
    disposition: "escalated",
    resolution_status: "handoff_in_progress",
    language: "Hindi",
    sentiment: "angry",
    intent: "human_transfer",
    confidence: 0.97,
    verification_state: "verified",
    failed_verification_attempts: 2,
    summary: "Repeated verification failures, customer requesting escalation.",
    escalation_reason: "Verification failures + angry sentiment",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: "live",
    started_at: "2026-06-24T10:11:00.000Z",
    ended_at: null,
    display_call_id: "C-001240",
    customer_name: "Pooja Nair",
    program_name: "Acme Insurance",
    duration_label: "07:45",
    display_status: "Escalated",
    agent_name: "Neha T.",
    agent_initials: "NT",
  },
  // Completed calls for history
  {
    id: "call-001233",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    queue_id: "queue-acme",
    customer_id: "customer-rohit",
    customer_phone: "+91 98765 43210",
    status: "completed",
    session_state: "resolved",
    disposition: "resolved",
    resolution_status: "resolved",
    language: "English",
    sentiment: "neutral",
    intent: "faq_answer",
    confidence: 0.94,
    verification_state: "not_required",
    failed_verification_attempts: 0,
    summary: "Policy renewal FAQ answered. Customer satisfied.",
    escalation_reason: "",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: null,
    started_at: "2026-06-24T09:50:00.000Z",
    ended_at: "2026-06-24T09:56:00.000Z",
    display_call_id: "C-001233",
    customer_name: "Rohit Sharma",
    program_name: "Acme Insurance",
    duration_label: "06:00",
    display_status: "Resolved",
  },
  {
    id: "call-001220",
    organization_id: "org-brightconnect",
    client_program_id: "program-healthplus",
    queue_id: "queue-healthplus",
    customer_id: "customer-neha",
    customer_phone: "+91 91234 56789",
    status: "completed",
    session_state: "resolved",
    disposition: "resolved",
    resolution_status: "resolved",
    language: "Hindi",
    sentiment: "neutral",
    intent: "case_status",
    confidence: 0.87,
    verification_state: "verified",
    failed_verification_attempts: 0,
    summary: "Reimbursement claim HLT-3007 status confirmed.",
    escalation_reason: "",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: null,
    started_at: "2026-06-24T09:30:00.000Z",
    ended_at: "2026-06-24T09:38:00.000Z",
    display_call_id: "C-001220",
    customer_name: "Neha Joshi",
    program_name: "HealthPlus",
    duration_label: "08:00",
    display_status: "Resolved",
  },
  {
    id: "call-001221",
    organization_id: "org-brightconnect",
    client_program_id: "program-travelsafe",
    queue_id: "queue-travelsafe",
    customer_id: "customer-vikram",
    customer_phone: "+91 90909 90909",
    status: "completed",
    session_state: "callback",
    disposition: "callback",
    resolution_status: "callback_pending",
    language: "English",
    sentiment: "neutral",
    intent: "callback_request",
    confidence: 0.93,
    verification_state: "verified",
    failed_verification_attempts: 0,
    summary: "Travel delay claim needs document review, callback scheduled.",
    escalation_reason: "",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: "callback",
    started_at: "2026-06-24T09:20:00.000Z",
    ended_at: "2026-06-24T09:25:00.000Z",
    display_call_id: "C-001221",
    customer_name: "Vikram Patel",
    program_name: "TravelSafe",
    duration_label: "05:00",
    display_status: "Callback",
  },
  {
    id: "call-001215",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    queue_id: "queue-acme",
    customer_id: "customer-arjun",
    customer_phone: "+91 99887 76655",
    status: "completed",
    session_state: "resolved",
    disposition: "resolved",
    resolution_status: "resolved",
    language: "English",
    sentiment: "neutral",
    intent: "new_complaint",
    confidence: 0.76,
    verification_state: "verified",
    failed_verification_attempts: 0,
    summary: "Premium payment issue logged and escalated to billing.",
    escalation_reason: "",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: null,
    started_at: "2026-06-24T09:00:00.000Z",
    ended_at: "2026-06-24T09:10:00.000Z",
    display_call_id: "C-001215",
    customer_name: "Arjun Mehta",
    program_name: "Acme Insurance",
    duration_label: "10:00",
    display_status: "Resolved",
  },
  {
    id: "call-001212",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    queue_id: "queue-acme",
    customer_id: "customer-suman",
    customer_phone: "+91 98765 43111",
    status: "completed",
    session_state: "resolved",
    disposition: "resolved",
    resolution_status: "resolved",
    language: "Hindi",
    sentiment: "neutral",
    intent: "faq_answer",
    confidence: 0.89,
    verification_state: "not_required",
    failed_verification_attempts: 0,
    summary: "Hindi FAQ answered for document submission timeline.",
    escalation_reason: "",
    recording_consent: true,
    ai_disclosure_acknowledged: true,
    handoff_mode: null,
    started_at: "2026-06-24T08:45:00.000Z",
    ended_at: "2026-06-24T08:50:00.000Z",
    display_call_id: "C-001212",
    customer_name: "Suman Verma",
    program_name: "Acme Insurance",
    duration_label: "05:00",
    display_status: "Resolved",
  },
];

export const demoCallTurns: Record<string, CallTurn[]> = {
  "call-001245": [
    {
      id: "turn-1",
      speaker: "ai",
      message:
        "Hello, you are speaking with VoiceOps Control for Acme Insurance. This conversation may be recorded. How can I help you today?",
      language: "English",
      confidence: 1,
      event_type: "system_disclosure",
      created_at: "2026-06-24T10:15:02.000Z",
    },
    {
      id: "turn-2",
      speaker: "customer",
      message: "I need a status update for claim CLM-9001.",
      language: "English",
      confidence: 1,
      event_type: "message",
      created_at: "2026-06-24T10:15:20.000Z",
    },
    {
      id: "turn-3",
      speaker: "ai",
      message: "Your claim CLM-9001 is currently under review. Assessor documents were received today.",
      language: "English",
      confidence: 0.88,
      event_type: "assistant_response",
      created_at: "2026-06-24T10:15:22.000Z",
    },
  ],
  "call-001243": [
    {
      id: "turn-10",
      speaker: "ai",
      message:
        "Hello, you are speaking with VoiceOps Control for HealthPlus. This conversation may be recorded. How can I help you today?",
      language: "Hindi",
      confidence: 1,
      event_type: "system_disclosure",
      created_at: "2026-06-24T10:12:02.000Z",
    },
    {
      id: "turn-11",
      speaker: "customer",
      message: "Why was my claim rejected?",
      language: "Hindi",
      confidence: 1,
      event_type: "message",
      created_at: "2026-06-24T10:13:15.000Z",
    },
    {
      id: "turn-12",
      speaker: "ai",
      message: "May I have your policy number please?",
      language: "Hindi",
      confidence: 0.95,
      event_type: "assistant_response",
      created_at: "2026-06-24T10:13:16.000Z",
    },
    {
      id: "turn-13",
      speaker: "customer",
      message: "Yes, it's HP123456789",
      language: "Hindi",
      confidence: 1,
      event_type: "message",
      created_at: "2026-06-24T10:13:30.000Z",
    },
    {
      id: "turn-14",
      speaker: "customer",
      message: "I want to speak to a human agent now.",
      language: "Hindi",
      confidence: 1,
      event_type: "message",
      created_at: "2026-06-24T10:14:00.000Z",
    },
    {
      id: "turn-15",
      speaker: "ai",
      message: "Connecting you to a live specialist now. Please hold for a moment.",
      language: "Hindi",
      confidence: 0.97,
      event_type: "assistant_response",
      created_at: "2026-06-24T10:14:01.000Z",
    },
  ],
  "call-001242": [
    {
      id: "turn-20",
      speaker: "customer",
      message: "My premium auto-debit failed last month and I want a refund of the late fee.",
      language: "English",
      confidence: 1,
      event_type: "message",
      created_at: "2026-06-24T10:10:05.000Z",
    },
    {
      id: "turn-21",
      speaker: "ai",
      message: "I understand. Let me connect you with a billing specialist who can resolve this directly.",
      language: "English",
      confidence: 0.79,
      event_type: "assistant_response",
      created_at: "2026-06-24T10:10:06.000Z",
    },
  ],
};

export const demoTickets: Ticket[] = [
  {
    id: "ticket-101",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    customer_id: "customer-suman",
    call_id: "call-001212",
    title: "Complaint about delayed document review",
    description: "Customer requested human follow-up in Hindi.",
    priority: "high",
    status: "open",
    created_by: "ai",
    assigned_to_membership_id: "membership-supervisor",
    created_at: "2026-06-24T08:50:00.000Z",
  },
  {
    id: "ticket-122",
    organization_id: "org-brightconnect",
    client_program_id: "program-healthplus",
    customer_id: "customer-neha",
    call_id: "call-001243",
    title: "Rejected claim appeal — VIP customer",
    description: "VIP member requested live specialist and supervisor review of claim rejection.",
    priority: "critical",
    status: "open",
    created_by: "ai",
    assigned_to_membership_id: "membership-supervisor",
    created_at: "2026-06-24T10:14:00.000Z",
  },
  {
    id: "ticket-115",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    customer_id: "customer-arjun",
    call_id: "call-001215",
    title: "Premium auto-debit failure — billing investigation",
    description: "Auto-debit failed in May, late fee applied. Customer requesting waiver.",
    priority: "medium",
    status: "open",
    created_by: "ai",
    assigned_to_membership_id: null,
    created_at: "2026-06-24T09:10:00.000Z",
  },
];

export const demoCallbacks: CallbackTask[] = [
  {
    id: "callback-98",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    customer_id: null,
    call_id: null,
    priority: "high",
    reason: "Premium refund dispute requires supervisor callback.",
    scheduled_for_label: "11:00 AM today",
    status: "pending",
    created_at: "2026-06-24T10:00:00.000Z",
    display_id: "CB-00098",
    customer_name: "Manish Gupta",
    program_name: "Acme Insurance",
    scheduled_time: "11:00 AM",
  },
  {
    id: "callback-97",
    organization_id: "org-brightconnect",
    client_program_id: "program-healthplus",
    customer_id: null,
    call_id: null,
    priority: "high",
    reason: "Benefits reimbursement pending document upload guidance.",
    scheduled_for_label: "11:15 AM today",
    status: "pending",
    created_at: "2026-06-24T10:05:00.000Z",
    display_id: "CB-00097",
    customer_name: "Priya Malhotra",
    program_name: "HealthPlus",
    scheduled_time: "11:15 AM",
  },
  {
    id: "callback-96",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    customer_id: null,
    call_id: null,
    priority: "medium",
    reason: "Policy renewal query, language preference Hindi.",
    scheduled_for_label: "11:30 AM today",
    status: "pending",
    created_at: "2026-06-24T10:08:00.000Z",
    display_id: "CB-00096",
    customer_name: "Ankit Singh",
    program_name: "Acme Insurance",
    scheduled_time: "11:30 AM",
  },
  {
    id: "callback-95",
    organization_id: "org-brightconnect",
    client_program_id: "program-travelsafe",
    customer_id: null,
    call_id: "call-001221",
    priority: "medium",
    reason: "Travel delay claim — awaiting document verification.",
    scheduled_for_label: "11:45 AM today",
    status: "pending",
    created_at: "2026-06-24T09:25:00.000Z",
    display_id: "CB-00095",
    customer_name: "Rakesh Iyer",
    program_name: "TravelSafe",
    scheduled_time: "11:45 AM",
  },
  {
    id: "callback-94",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    customer_id: null,
    call_id: null,
    priority: "low",
    reason: "General inquiry about new policy add-ons.",
    scheduled_for_label: "12:00 PM today",
    status: "pending",
    created_at: "2026-06-24T10:10:00.000Z",
    display_id: "CB-00094",
    customer_name: "Deepa R.",
    program_name: "Acme Insurance",
    scheduled_time: "12:00 PM",
  },
];

export const demoReviews: QAReview[] = [
  {
    id: "review-76",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    call_id: "call-001233",
    reviewer_membership_id: null,
    score: null,
    status: "pending",
    flags: ["needs_review"],
    notes: "New call routed to QA queue, awaiting reviewer assignment.",
    created_at: "2026-06-24T10:05:00.000Z",
    display_id: "QA-00076",
    agent_name: "Pooja S.",
    program_name: "Acme Insurance",
    call_display_id: "C-001233",
    date_label: "24 Jun, 10:05 AM",
  },
  {
    id: "review-75",
    organization_id: "org-brightconnect",
    client_program_id: "program-healthplus",
    call_id: "call-001220",
    reviewer_membership_id: null,
    score: null,
    status: "pending",
    flags: ["needs_review"],
    notes: "Awaiting QA review. Hindi verification flow.",
    created_at: "2026-06-24T09:52:00.000Z",
    display_id: "QA-00075",
    agent_name: "Rohit K.",
    program_name: "HealthPlus",
    call_display_id: "C-001220",
    date_label: "24 Jun, 09:52 AM",
  },
  {
    id: "review-74",
    organization_id: "org-brightconnect",
    client_program_id: "program-travelsafe",
    call_id: "call-001221",
    reviewer_membership_id: "membership-qa",
    score: 78,
    status: "in_review",
    flags: ["callback_delay"],
    notes: "Callback scheduling delayed. Coaching required on urgency cues.",
    created_at: "2026-06-24T09:41:00.000Z",
    display_id: "QA-00074",
    agent_name: "Neha T.",
    program_name: "TravelSafe",
    call_display_id: "C-001221",
    date_label: "24 Jun, 09:41 AM",
  },
  {
    id: "review-73",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    call_id: "call-001215",
    reviewer_membership_id: "membership-qa",
    score: 52,
    status: "reviewed",
    flags: ["missed_disclosure_timing", "low_score"],
    notes: "Disclosure given late. Score below threshold. Coaching scheduled.",
    created_at: "2026-06-24T09:30:00.000Z",
    display_id: "QA-00073",
    agent_name: "Arjun M.",
    program_name: "Acme Insurance",
    call_display_id: "C-001215",
    date_label: "24 Jun, 09:30 AM",
  },
  {
    id: "review-72",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    call_id: "call-001212",
    reviewer_membership_id: "membership-qa",
    score: 88,
    status: "reviewed",
    flags: ["clear_disclosure"],
    notes: "Strong verification, concise FAQ delivery. No coaching needed.",
    created_at: "2026-06-24T09:12:00.000Z",
    display_id: "QA-00072",
    agent_name: "Suman V.",
    program_name: "Acme Insurance",
    call_display_id: "C-001212",
    date_label: "24 Jun, 09:12 AM",
  },
];

export const demoKnowledge: KnowledgeDocument[] = [
  {
    id: "doc-1",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    title: "Claim FAQ",
    source_type: "faq",
    status: "active",
    languages: ["English", "Hindi"],
    tags: ["claims", "faq"],
    created_at: "2026-06-24T06:00:00.000Z",
  },
  {
    id: "doc-2",
    organization_id: "org-brightconnect",
    client_program_id: "program-acme",
    title: "Required Documents",
    source_type: "sop",
    status: "active",
    languages: ["English", "Hindi"],
    tags: ["documents", "claim"],
    created_at: "2026-06-24T06:10:00.000Z",
  },
  {
    id: "doc-3",
    organization_id: "org-brightconnect",
    client_program_id: "program-healthplus",
    title: "Reimbursement SOP",
    source_type: "sop",
    status: "active",
    languages: ["English", "Hindi"],
    tags: ["reimbursement", "health"],
    created_at: "2026-06-24T06:20:00.000Z",
  },
  {
    id: "doc-4",
    organization_id: "org-brightconnect",
    client_program_id: "program-travelsafe",
    title: "Travel Claim Guidelines",
    source_type: "faq",
    status: "active",
    languages: ["English"],
    tags: ["travel", "claim", "cancellation"],
    created_at: "2026-06-24T06:30:00.000Z",
  },
];

export const demoAnalytics: AnalyticsSnapshot = {
  live_calls: 3,
  queue_depth: 3,
  resolved_today: 30,
  resolved_yesterday: 18,
  callbacks_pending: 7,
  escalations_today: 6,
  escalations_yesterday: 3,
  tickets_open: 5,
  qa_pending: 3,
  avg_handle_time: "5:24",
  csat_score: 4.1,
  top_intents: [
    { intent: "case_status",      count: 48, share: 40 },
    { intent: "faq_answer",       count: 28, share: 23 },
    { intent: "new_complaint",    count: 21, share: 18 },
    { intent: "callback_request", count: 15, share: 12 },
    { intent: "human_transfer",   count: 9,  share: 7  },
  ],
  dispositions: [
    { label: "Resolved",  count: 30, color: "#0f7b77" },
    { label: "Callback",  count: 8,  color: "#6366f1" },
    { label: "Escalated", count: 6,  color: "#bb5f33" },
    { label: "Ticket",    count: 4,  color: "#f59e0b" },
    { label: "Open",      count: 3,  color: "#94a3b8" },
  ],
  sentiment_mix: [
    { label: "neutral",  count: 38 },
    { label: "angry",    count: 15 },
    { label: "positive", count: 10 },
  ],
};
